### ISSUE TITLE
[Problem] cannot open julia snail

### ISSUE THREAD

**Issue by nesteiner** [gcv/julia-snail#103]
https://user-images.githubusercontent.com/46296608/180594733-d864cfe3-75ad-45e2-b90d-14333a46ebf3.mp4

take a look at this, I don't know what's going on

**Comment by nesteiner** [comment]
this is my configure code, it suddenly turn into that, I don't know how
```emacs-lisp
(use-package julia-mode
  :hook (julia-mode . julia-snail-mode)
  :config
  (setq julia-repl-switches nil
	julia-snail-extra-args nil
	julia-indent-offset 2)

  (setenv "JULIA_PKG_SERVER" "https://mirrors.tuna.tsinghua.edu.cn/julia")
  (setq-default julia-snail-extra-args "--sysimage /home/steiner/.julia/images/julia-dev.so")
  (setq-default	julia-snail-executable "/home/steiner/.local/bin/julia")

  :commands julia-snail-mode)

(provide 'init-julia)
```

**Comment by gcv** [comment]
Is there anything interesting in `*Messages*`? What happens when you run

```
$ /home/steiner/.local/bin/julia --sysimage /home/steiner/.julia/images/julia-dev.so
```

directly in the shell?

**Comment by nesteiner** [comment]
nope.
it works well

**Comment by gcv** [comment]
What is the output in Emacs of calling the `(julia-snail--launch-command)` function (using <kbd>M-:</kbd> or ielm)? Can you run that exact command from the shell?

**Comment by nesteiner** [comment]
![Uploading image.png…]()

here you are

**Comment by gcv** [comment]
So just running Julia with your image works, but combining the image with the JuliaSnail.jl does not, rIght? What happens if you omit the image? 

```
$ /home/steiner/.local/bin/julia -L /home/steiner/.emacs.d/elpa/julia-snail-20220722.547/JuliaSnail.jl
```

**Comment by nesteiner** [comment]
![image](https://user-images.githubusercontent.com/46296608/180609505-836b78f4-113c-4821-96dc-593cb187a3c4.png)

**Comment by gcv** [comment]
Since the image works when separated from Snail, and Snail works when separated from the image, it looks like a dependency incompatibility between your image and Snail. The error message above suggests (re)installing XML2. Maybe start there? You should probably rebuild your image and make sure it includes the latest Snail (as well as the XML2 dependency, though I do not know where it comes from).

I never managed to get Julia images working correctly (see #84), so I don't have more specific help to offer.

**Comment by nesteiner** [comment]
no no no, I upload the wrong image, it is here 
![image](https://user-images.githubusercontent.com/46296608/180610312-e48fb07e-c877-4f48-a0e2-dd2952f78e5c.png)


I have fix it, the image is not updated, after updating, everything works well

**Comment by gcv** [comment]
Great!
