### ISSUE TITLE
Allow interrupting long-running Julia tasks

### ISSUE THREAD

**Issue by gcv** [gcv/julia-snail#104]
Right now, a computation kicked off using any of the `julia-snail-send-*` commands cannot be interrupted.

**Comment by MasonProtter** [comment]
I think the solution to this is just having an interrupt function which does `Base.throwto(julia_snail_task, InterruptException())`. Does julia-snail already have a separate task it uses for evaluation?

**Comment by gcv** [comment]
Nope, no separate tasks for evaluation. :( I agree that's a good approach.

**Comment by MasonProtter** [comment]
Probably what you should do is launch the computation in a task, and then have another task that checks every `n` miliseconds if the task is completed, and if it is completed you `fetch` it. 

You can then stick a hook into that secondary task that does the interruption if needed.

**Comment by gcv** [comment]
This is fixed in a88755d. Or so I hope! Snail now runs evaluations sent on its wire protocol in separate Julia tasks, and they're tracked and interruptible using <kbd>M-x julia-snail-interrupt-task</kbd>. The change will be in MELPA in a couple of hours. Feedback and bug reports welcome.
