### ISSUE TITLE
Multimedia buffer not being used with `julia-snail-send` commands.

### ISSUE THREAD

**Issue by MasonProtter** [gcv/julia-snail#114]
If I do `M-x julia-snail-send-line` on a line which returns a plot object, I'm not getting it displayed in the multimedia buffer. Just like in the REPL, I need to wrap it in a `display` call, and the README seems to contradict that.

**Comment by gcv** [comment]
It should be the opposite: in the REPL, you should _not_ need the `display` wrapper. From Emacs (e.g. using `julia-snail-send-line`) you do. Can you please verify that the multimedia buffer works _without_ `display` from the REPL?

**Comment by gcv** [comment]
Please reopen if there's more information.
