### ISSUE TITLE
[Question] how to abort evaluating ?

### ISSUE THREAD

**Issue by nesteiner** [gcv/julia-snail#115]
when evaluating a code block, it stuck the julia-snail, and I want to cancel it, how should I do

**Comment by gcv** [comment]
You mean the Julia side computation takes a long time?

**Comment by gcv** [comment]
To clarify, if it’s a matter of aborting long-running Julia tasks, then it’s a known problem in Snail (#104). Shouldn’t be too difficult to resolve, I just don’t have time right now.

If you’re seeing tasks that should be quick hanging, then it’s usually a bug in Snail. I’ll need a reproducible case.

**Comment by gcv** [comment]
Please reopen if there's more information.
