### ISSUE TITLE
Not compatible without package.el

### ISSUE THREAD

**Issue by mfiano** [gcv/julia-snail#122]
The REPL fails to start automatically for me, due to no such function `package-installed-p`, which is only present when `package.el` is installed, which does not combine well with `straight.el`.

https://github.com/gcv/julia-snail/blob/117f62123bf168043fb9ab5df953ee444460afd9/julia-snail.el#L1855-L1856

**Comment by mfiano** [comment]
Hi, thanks for the quick response and for this library. After using LS.jl for a while, I am very happy with the user experience this package provides.

On the bug, your proposed changes due infact resolve the issue. However, the REPL still does not start automatically. There are no relevant `*Messages*`, and loading JuliaSnail.jl manually with `julia -L` succeeds without failure. `julia-snail-executable` is set to an absolute path string (`/usr/bin/julia`, which exists). I am able to start the server with `M-x julia-snail` manually. Does any of this sound familiar?

This is not a deal breaker or anything. I am not really bothered by having to initiate the package with a keybinding. If you would like to debug this further though, I could certainly move this discussion to another thread if that is preferred. Thanks again!

**Comment by gcv** [comment]
The REPL isn't supposed to start automatically. Snail's inspirations (Slime and CIDER) don't do this (at least not by default), and I personally find that level of tool automation intrusive. It should be possible to rig something together and make it an opt-in feature, but I don't have anything like that planned at the moment.

**Comment by mfiano** [comment]
Actually, I do prefer it this way and agree with you 100%. The problem was that I misread the documentation. I am a long time CL user of SLIME/SLY, and I like the direction you are taking this very much.
