### ISSUE TITLE
Adding sshx for tramp

### ISSUE THREAD

**Issue by kadir-gunel** [gcv/julia-snail#125]
Hello, I am struggling to connect tramp via ssh but I can do sshx without any problems. I searched and configured ton of stuff. And no hope with ssh.  I saw above that you added ```scp``` and ```scpx```. Is it possible for you to add ```sshx``` as well ? Or are there any problems with ```sshx``` ?  

B.R.

_Originally posted by @kadir-gunel in https://github.com/gcv/julia-snail/issues/120#issuecomment-1641863386_

**Comment by gcv** [comment]
A little local testing didn't turn up any problems for me with `sshx`, so I just whitelisted it (commit 18b891b4). It should reach MELPA in a couple of hours.

Please try it out and let me know if it works for you.

**Comment by kadir-gunel** [comment]
Thank you for quick response. 

Now, I can cal ```julia-snail``` on remote. But,  it keeps telling me to set the ```julia-snail-executable``` which I did; on both machines the path for executable is same (```/usr/local/bin/julia```). 
I read the readme file of yours and probably the reason for not calling julia on remote is that I am using fish shell with tmux (both local and remote). And I am paying the price right now :) 

 I don't know if you are familiar with tramp but I also set the remote shell by using the ```(setq tramp-default-remote-shell "/usr/bin/bash")```. Still no hope. 

 Do you have any solution for this?

**Comment by kadir-gunel** [comment]
For some reason, I managed to connect to remote using ```ssh```. All I have to do is to add  inside config.fish file : 

```bash
if test "$TERM" = "dumb"
    exec sh
end
```
 Then I managed to connect to the remote server. But still I am getting ``` ....; double-check julia-snail-executable path``` error/warning. 


Any suggestions ?

**Comment by gcv** [comment]
That part of the readme is for people who want to pick up the location of `julia` from the remote shell’s path, and it gives hints about how to configure the remote shell appropriately. Path setup for different types of shells is surprisingly complex, and I think setting up `julia-snail-executable` in your remote project’s `.dir-locals.el` is much easier.

Please follow the debugging steps here: https://github.com/gcv/julia-snail/issues/120#issuecomment-1524731711

**Comment by kadir-gunel** [comment]
I copied and pasted as a comment inside "remote".jl file and it returned me : 

``` ssh -t -L 10011:localhost:10011 phd@192.168.1.133#52347 /usr/local/bin/julia  -L /tmp/julia-snail-d8f1d20ea24483f4e15d0b570cacc558958544c70dc1ddd6bdfc7be94ef1d7fe/JuliaSnail.jl"``` 

Then copied and pasted this line to iterm  and immediately it connected to remote shell's tmux session without opening Julia's REPL. Strangely, when I detach it from tmux session I am able to open remote REPL. So the problem is caused by tmux then, right?  Is there any trick to bypass it ?  

I also created a ```.dir_locals.el``` file under project folder and wrote : 
``` (setq julia-snail-executable "/usr/local/bin/julia") ``` but I still cannot run remote Julia repl.

**Comment by gcv** [comment]
It certainly looks like tmux is causing the problem. Is it being launched by a `RemoteCommand` section in your `.ssh/config` file? If so, then maybe try adding `-o RemoteCommand=none` to the ssh invocation above and see if it helps.

**Comment by kadir-gunel** [comment]
Strangely, `-o RemoteCommand=none` does not help. Whatever I do it somehow enters the tmux session. This is really annoying ...

**Comment by gcv** [comment]
You need to get tmux out of the picture. It’s not supported for remote Snail Julia REPLs. That may happen in the future, but the work is not currently planned.

tmux is clearly set up in your remote environment to automatically start (or connect to an existing session). Please double-check your `.ssh/config` file and your shell startup scripts for what could be causing it to start. Maybe try running `ssh` with the `-vv` flag (verbose mode) to see what’s going on and what SSH is doing when it connects.

**Comment by kadir-gunel** [comment]
thank you very much for everything.
