### ISSUE TITLE
problem with julia-snail-send-buffer-file

### ISSUE THREAD

**Issue by dahtah** [gcv/julia-snail#13]
This issue appears a bit non-deterministically but here's a minimal reproducing example:
1. open a one-line .jl file  with an error, eg.
```julia
factorial(1.2)
```
2. Hit C-c C-z, then C-c C-k. The error buffer appears (as expected)
3. Comment out the error, then C-c C-k: the message "xyz.jl loaded" appears
4. Uncomment, reinserting the error, then C-c C-k
5. Comment again, C-c C-k ("xyz.jl loaded")
6. Uncomment, C-c C-k: the message "xyz.jl loaded" appears, incorrectly

julia-snail-send-region doesn't seem to be affected.

**Comment by gcv** [comment]
I can't reproduce it. 😕 Are you sure you saved the file after uncommenting the offending line? I should probably put in a check for that...

If you can reproduce it in a fresh session and making sure you save after every change, please attach the contents of the `*julia* process` buffer.

**Comment by gcv** [comment]
I added an explicit check for unsaved files to `julia-snail-send-buffer-file` in d5425ed. Please reopen if you still run into trouble.
