### ISSUE TITLE
Consecutive super/subscript completion

### ISSUE THREAD

**Issue by hatmatrix** [gcv/julia-snail#131]
Hello, thanks for this excellent package!

I found out that Julia [supports consecutive super/subscript completion](https://github.com/JuliaLang/julia/pull/38649). Typing for instance, `x\_123<tab>` produces `x₁₂₃` in the REPL. However, I don't get this behavior in the Emacs script file (nothing happens when I hit `<tab>`) I also tested in VS Code and don't get that either (there, hitting `<tab>` just enters tab character).

Is there something that needs to be added specifically to the editor or it's just something difficult to implement?

**Comment by gcv** [comment]
It should be possible to make Emacs do this, but it's a matter for [julia-mode](https://github.com/JuliaEditorSupport/julia-emacs), as Snail relies on it for code formatting.

**Comment by hatmatrix** [comment]
Thanks a lot. I [see](https://github.com/JuliaEditorSupport/julia-emacs/blob/master/julia-mode-latexsubs.el) every entry for these characters are included manually so maybe difficult to implement but will check.

**Comment by gcv** [comment]
Closing as there isn't anything to do on the Snail side.
