### ISSUE TITLE
Can't start Julia after update "The vterm buffer is inactive"

### ISSUE THREAD

**Issue by nlw0** [gcv/julia-snail#132]
I've upgraded to Emacs 29, and I've also started using straight-use-package. I'm having lots of issues, but it seems so close. I think all dependencies are right, I can run vterm. julia-snail can't start running julia, though, I get the "vterm buffer is inactive" error. I can call `julia -L .../JuliaSnail.jl` from the terminal, though. What else can I do to debug this?

**Comment by gcv** [comment]
When terminal invocation works but startup fails in Emacs, it usually means Emacs can’t find the `julia` binary. Is its location part of `exec-path`? Check by looking at the output of <kbd>M-:</kbd>`exec-path`.

**Comment by gcv** [comment]
Please reopen if this is still a problem.

**Comment by nlw0** [comment]
Sorry I never came back to this, in the end I think it was about getting vterm and other dependencies to work first, the other maybe was related to the popup thing.
