### ISSUE TITLE
Starting Snail collides with existing Eat buffer

### ISSUE THREAD

**Issue by berquist** [gcv/julia-snail#133]
I had an Eat session open with the default name of `*eat*`.  Starting Snail picked it up, changed the name, and started sending strings to it:
![Screenshot from 2023-11-11 15-34-18](https://github.com/gcv/julia-snail/assets/727571/ad02499f-db75-406a-8de7-589a544885d9)

It looks like the behavior is to find an existing Eat session rather than always creating a new one.  A better behavior would be to look for the buffer named `julia-snail-repl-buffer`.

I am willing to try fixing this.

**Comment by gcv** [comment]
Oh my 🤦. I think that's an Eat default behavior, but I'm pretty sure it could be easily worked around. It would be great if you could send me a PR for this!
