### ISSUE TITLE
formatter exenstion Multibyte character error

### ISSUE THREAD

**Issue by mstenek** [gcv/julia-snail#136]
Hello

I'm getting this error `format: Multibyte character in data for base64 encoding` when I try to use `julia-snail/formatter-format-buffer`.

Editing the following

```elisp
(defun julia-snail/formatter--format-text (txt)
  (julia-snail--send-to-server
    '("JuliaSnail" "Extensions" "Formatter")
    (let ((ubs (string-as-unibyte txt)))
      (format "format_data(\"%s\")" (base64-encode-string ubs)))
    :async nil))
```
to include the `string-as-unibyte` bit, fixes the issue. Is this correct?

**Comment by gcv** [comment]
Seems reasonable. Feel free to open a PR.
