### ISSUE TITLE
OhMyREPL.jl package not working 

### ISSUE THREAD

**Issue by Aneeqasif** [gcv/julia-snail#140]
it works perfectly in vterm and then opening julia repl. but not in julia snail repl. any guess what  am i missing.

**Comment by gcv** [comment]
This took a bit of digging, but OhMyREPL does not initialize itself when the `julia` binary runs with command-line arguments (see https://github.com/KristofferC/OhMyREPL.jl/blob/78a4d87e845dd930e8ed2cbb741a6dc59a47a75a/src/OhMyREPL.jl#L106). You can reproduce it by doing `julia -L myfile.jl` and then running `using OhMyREPL`: it won’t work. Snail relies on command -line arguments to load itself.

You might want to open a ticket with the OhMyREPL maintainers and ask why they enforce this restriction.

**Comment by Aneeqasif** [comment]
Ok sure, i am submitting a ticket on ohmyrepl repo now regarding this i hope there is some workaround that devs may offer

**Comment by gcv** [comment]
I just pushed a change to Snail following advice on the OhMyREPL ticket. It'll hit MELPA in a couple of hours. When it shows up, please update Snail and see if that fixes the problem for you.

**Comment by Aneeqasif** [comment]
thank you so much for addressing this issue.
