### ISSUE TITLE
Problem with output of "missing"?

### ISSUE THREAD

**Issue by dojt** [gcv/julia-snail#143]
Is it possible that producing the output "missing" via C-c C-l or C-c C-r doesn't work? The following is displayed in the `*julia* error` buffer:

```
TypeError: non-boolean (Missing) used in boolean context

format(obj::Missing, width::Int64, height::Int64) at JuliaSnail.jl:148
eval_tmpfile(tmpfile::String, modpath::Vector{Symbol}, realfile::String, linenum::Int64, popup_params::Main.JuliaSnail.PopupDisplay.Params) at JuliaSnail.jl:265
top-level scope at none:1
eval at boot.jl:385 [inlined]
eval_in_module(fully_qualified_module_name::Vector{Symbol}, expr::Expr) at JuliaSnail.jl:226
(::Main.JuliaSnail.var"#30#36"{Sockets.TCPSocket})() at JuliaSnail.jl:913
```

What I did to produce that was to load a file containing nothing else but the word "missing" (plus newline), start `julia-snail-mode`, open the `*julia*` buffer with C-c C-z and then hit C-c C-l on the line with the word "missing".

My Julia Snail version:
* 20240201.637

My Emacs:
* GNU Emacs 29.2 (build 1, aarch64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6.6 (Build 21G646)) of 2024-01-18

**Comment by gcv** [comment]
Should be fixed in https://github.com/gcv/julia-snail/commit/ce6994a548c3da051eb9104cad2c1056aa3cf4c1. It's in MELPA now. Please let me know if it works for you.

**Comment by gcv** [comment]
Please reopen if this is still a problem.
