### ISSUE TITLE
add post-formatting sync/revert of buffer

### ISSUE THREAD

**Issue by just-walk** [gcv/julia-snail#144]
When using JuliaFormatter.jl to format the buffer, the file is written externally by JuliaFormatter.jl, which leads to Emacs noting the buffer as modified/out-of-date with the file. It may be a nice feature to have it revert by default or somehow update the buffer as not modified. This would be particularly useful in the case where you add an after-save hook on .jl files to run the formatter. As it is, if you run the formatter with such a hook, then you are in a position where the buffer can never be unmodified without a manual revert.

**Comment by gcv** [comment]
Do you still have this problem if you enable `global-auto-revert-mode`? Or maybe selectively enable `auto-revert-mode` for `julia-mode` files? It's intrusive IMO to forcibly enable it through Snail, but I can add a note to this effect to the documentation of the formatter extension.

**Comment by just-walk** [comment]
I have `auto-revert-mode` on by default for `julia-mode`.

I think I was making a major conceptual mistake in thinking  that `julia-snail/formatter-format-buffer` will format the file, like running JuliaFormatter.jl externally will. That explains why the buffer is always seen as modified: I was modifying it with this hook to run the formatter. I suppose a solution for what I want would be to use the [julia-formatter.el](https://codeberg.org/FelipeLema/julia-formatter.el) and configure it to format the file on save.
