### ISSUE TITLE
Image display

### ISSUE THREAD

**Issue by non-Jedi** [gcv/julia-snail#15]
One of the nice things about [emacs-jupyter](https://github.com/dzop/emacs-jupyter) which I currently use for a julia REPL is that it ties into Julia's [multimedia display system](https://docs.julialang.org/en/v1/base/io-network/#Multimedia-I/O-1) via IJulia to give inline display of images. Do you see a path to doing the same with julia-snail's current architecture, or would that require "reimplementing the REPL in elisp" as you discussed on the forums? Example image from several months ago with emacs-jupyter REPL below for reference:

![ck7Q4Tu](https://user-images.githubusercontent.com/17915621/78200195-e3263780-745b-11ea-8c72-a9e80da9e48a.jpg)

**Comment by gcv** [comment]
It depends on what would be considered an acceptable form of image display. True inline like in the screenshot would require an Elisp REPL implementation. But if popping up Emacs buffers with rendered images would be acceptable, then I think it's mostly a matter of implementing a Snail-aware subtype of Julia's `Base.Multimedia.AbstractDisplay` and bundling it with Snail.

**Comment by non-Jedi** [comment]
Both inline and in a seperate buffer are nice to have tbh for different purposes.

**Comment by benide** [comment]
I would definitely make use of it popping up in a separate buffer. Inline would be nice too, but for me, the easier option sounds totally fine. Also, just wanted to say that the features you already have implemented are working well for me! Nice work!

**Comment by gcv** [comment]
Thank you for your kind words.

I have to think some more about how to implement it, and it's definitely a planned feature.

**Comment by dahtah** [comment]
I have a pull request open with some basic functionality, if anyone wants to try it out

**Comment by gcv** [comment]
Took a while, but Snail now supports the Julia multimedia interface! See commit 2753be5 and [the documentation](https://github.com/gcv/julia-snail#multimedia-and-plotting).
