### ISSUE TITLE
Executing blocks other than function ... end?

### ISSUE THREAD

**Issue by wenzlawski** [gcv/julia-snail#153]
How can one send begin ... end, if, or while blocks to the REPL? What about multiline function calls?

Sending a function to the repl with `julia-snail-send-top-level` or `julia-snail-send-dwim` works, but anything other block just terminates with `No top-level form at point`. Is this normal behaviour, or is something wrong with the way I'm using it? 

The way I am currently using it is highlighting every block (except function), and executing with `julia-snail-send-region`. This works but its cumbersome.

**Comment by Sabancay** [comment]
I recommend using expreg to select regions. It uses treesitter. Mark paragraph often gives a good selection candidate, when the code is strctured by new lines.

I use the following keys/commands to select:

:map julia-ts-mode-map
	    ("C-c p"    . mark-paragraph)
	    ("C-c f"     . mark-defun)
	    ("C-+"       . expreg-expand)
	    ("C--"        . expreg-contract)

  and these to feed the REPL:

	 :map julia-snail-mode-map
	    ("S-<return>"   . julia-snail-send-dwim)
	    ("C-<return>"   . julia-snail-send-region)
	    ("M-<return>"   . julia-snail-send-line)
	    ("C-S-<return>" . julia-snail-send-buffer-file)

**Comment by wenzlawski** [comment]
Expreg is just what I was looking for. Thank you!
