### ISSUE TITLE
Repl-History Search And Yank fails when using eat-terminal

### ISSUE THREAD

**Issue by Sabancay** [gcv/julia-snail#154]
Emacs: 29.2
snail: julia-snail-20240310.1510
eat: eat-0.9.4
Command: julia-snail/repl-history-search-and-yank

Debugger entered--Lisp error: (void-function vterm-insert)
  (vterm-insert res)
  (if (symbol-value julia-snail-repl-mode) (vterm-insert res) (insert res))
  (let* ((hst (julia-snail/repl-history--fetch n)) (res (completing-read "Julia REPL history search: " hst))) (if (symbol-value julia-snail-repl-mode) (vterm-insert res) (insert res)))
  (progn (if --cl-rest-- (signal 'wrong-number-of-arguments (list 'julia-snail/repl-history-search-and-yank (+ 1 (length --cl-rest--))))) (let* ((hst (julia-snail/repl-history--fetch n)) (res (completing-read "Julia REPL history search: " hst))) (if (symbol-value julia-snail-repl-mode) (vterm-insert res) (insert res))))
  (let* ((n (if --cl-rest-- (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--)))) julia-snail/repl-history-default-size))) (progn (if --cl-rest-- (signal 'wrong-number-of-arguments (list 'julia-snail/repl-history-search-and-yank (+ 1 (length --cl-rest--))))) (let* ((hst (julia-snail/repl-history--fetch n)) (res (completing-read "Julia REPL history search: " hst))) (if (symbol-value julia-snail-repl-mode) (vterm-insert res) (insert res)))))
  julia-snail/repl-history-search-and-yank()
  funcall-interactively(julia-snail/repl-history-search-and-yank)
  command-execute(julia-snail/repl-history-search-and-yank record)
  #<subr execute-extended-command>(nil "julia-snail/repl-history-search-and-yank" nil)
  ad-Advice-execute-extended-command(#<subr execute-extended-command> nil "julia-snail/repl-history-search-and-yank" nil)
  apply(ad-Advice-execute-extended-command #<subr execute-extended-command> (nil "julia-snail/repl-history-search-and-yank" nil))
  execute-extended-command(nil "julia-snail/repl-history-search-and-yank" nil)
  funcall-interactively(execute-extended-command nil "julia-snail/repl-history-search-and-yank" nil)
  command-execute(execute-extended-command)

**Comment by gcv** [comment]
Should be fixed in https://github.com/gcv/julia-snail/commit/a63ee2a61efd6af2d6a597bfa40cc98630406a8e, which will hit MELPA in a couple of hours. Please try it and let me know if it works for you.

**Comment by Sabancay** [comment]
Thank you - works.
