### ISSUE TITLE
Use Emacs local variable to specify parent source file

### ISSUE THREAD

**Issue by zengmao** [gcv/julia-snail#170]
Currently, julia-snail is only aware of the module that an "included" file belongs to after the user evaluates the parent file by `C-c C-k`. It would be nice to specify the "master file" by an Emacs local variable, similar to how AUCTeX uses local variables to infer the master file for multi-file LaTeX documents:
https://www.gnu.org/software/auctex/manual/auctex/Multifile.html

**Comment by zengmao** [comment]
Knowing only a little eLisp, it seems that `julia-snail--module-for-file` in `julia-snail.el` is the function to be tweaked if one tries to implement this?

**Comment by gcv** [comment]
I like the general idea, but I’m not clear on how nested modules should be handled. I guess you could set a local variable in each file pointing to its containing “parent”?

You are correct that `julia-snail--module-for-file` is the place to look. You should probably look at `julia-snail--module-merge-includes` also, since it deals with the internal data structure that maintains the module cache (`julia-snail--cache-proc-implicit-file-module`).

**Comment by zengmao** [comment]
To avoid Emacs-specific annotations appearing in Julia source files (which may be undesirable for collaborators who use other editors or IDEs), you could use directory-local variables specified in `.dir-locals.el` to store a hash table which maps every child file to its parent file. Some `.jl` files, e.g. scripts files, don't have parent files, and won't appear in the aforementioned hash table.

Here's another workaround which avoids `C-c C-k`: I just run a trimmed down version of `julia-snail-send-buffer-file` which only analyzes the "include" structures but doesn't run the code:
```
(defun julia-snail-analyze-includes ()
  "Analyze the current buffer's file for include statements"
  (interactive)
  (let* ((filename (julia-snail--efn (buffer-file-name (buffer-base-buffer))))
         (includes (julia-snail--cst-includes (current-buffer))))
    (when (or (not (buffer-modified-p))
              (y-or-n-p (format "'%s' is not saved, analyze in Julia anyway? " filename)))
      (if (eq :error includes)
          (let ((error-buffer
                 (julia-snail--message-buffer
                  repl-buf
                  "error"
                  (concat filename
                          " analyzed in Julia, but the Snail parser failed."))))
            (pop-to-buffer error-buffer))
        (julia-snail--module-merge-includes filename includes)))))
```

This workaround is useful to me because I've encountered strange (registered) packages which can only be `import`'ed but not `include`'d, due to some weird use of Pkg internals by the package.

**Comment by gcv** [comment]
I think your PR is a good approach. Cloning the entire set of module relationships in a `.dir-locals.el` seems pretty fragile to me. I’ll close this ticket as done with your PR merged in, but feel free to reopen if you want to discuss it more.
