### ISSUE TITLE
Completion always offers unexported names with names(all=true)

### ISSUE THREAD

**Issue by christopher-dG** [gcv/julia-snail#23]
When I type `UV_`, I expect to get no completion suggestions because there are no top-level symbols that start with `UV_`. However, there are a bunch of `Base.UV_*` constants, which I would expect to complete if I typed `Base.UV_`.

JuliaSnail appears to be doing all of its completion with `names(module; all=true)`. I didn't look too closely at the implementation, but would it be possible to do `all=true` only if the completion prefix is `Mod.xyz` and `all=false` if the prefix is just `xyz`?

**Comment by christopher-dG** [comment]
Ah I see that this is mostly being addressed in #22!

**Comment by gcv** [comment]
This should all be fixed now. Please reopen if something still looks wrong.
