### ISSUE TITLE
JuliaSnail.lsnames causes some irrelevant warnings to appear in REPL

### ISSUE THREAD

**Issue by orialb** [gcv/julia-snail#27]
It seems that somehow `JuliaSnail.lsnames` causes irrelevant deprecation warnings to appear in the REPL, which can be quite disturbing as it is called often for code completion. 

An example I encountered:
1. open snail REPL
2. load latest Revise version (`using Revise`)
3. run ` JuliaSnail.lsnames(Main, all=true, imported=true, include_modules=true, recursive=true);`

This results in:
![image](https://user-images.githubusercontent.com/1208196/80616986-d3414980-8a41-11ea-86c0-129279fb40a9.png)

I also encountered other warnings from other packages appearing in the REPL for no apparent reason before, and I now suspect it is related to `lsnames`.

**Comment by gcv** [comment]
I bet Julia throws a warning when you look at a deprecated name. `lsnames` needs to be smarter about it, and exclude those somehow.

**Comment by orialb** [comment]
would redirecting stderr to a temp file using `redirect_stderr` inside `lsnames` be acceptable? That's the only way so far I managed to disable these warnings, but maybe I'm missing something.

**Comment by orialb** [comment]
Here is a concrete suggestion (that I need to test a bit), define a macro to redirect stderr in JuliaSnail:
```julia
macro no_stderr(expr)
    return quote
        original_stderr = stderr
        _, temp_stderr = redirect_stderr()
        try
            $(esc(expr))
        finally
            redirect_stderr(original_stderr)
            close(temp_stderr)
        end
    end
end
```

then call 
```elisp
(julia-snail--send-to-server
       module
       (format "Main.JuliaSnail.@no_stderr Main.JuliaSnail.lsnames(%s, all=true, imported=true, include_modules=true, recursive=true)" ns)
       :async nil)
```
in `julia-snail--completions`. 
It should be also possible to redirect stderr inside `lsnames` but since it is recursive it might be better to just do the redirection once outside of `lsnames`. 

From a quick check I did, this makes the warnings go away. 
I can open a PR if you think it is acceptable solution.

**Comment by gcv** [comment]
Let's leave the stderr solution as an option for now.

From my hasty look at the implementation of deprecations, https://github.com/JuliaLang/julia/blob/master/base/deprecated.jl, `@deprecated` swaps a function with wrapper which prints the complaint. Since we don't call the functions in question, `lsnames` shouldn't do anything for deprecated functions.

Then I looked at your example, and it seems to complain about deprecated modules, not functions. `Revise.FileModules` is a module, and it seems to be marked with `Base.@deprecate_binding` in the Revise source. I don't have time to dig deep into it right now, but that macro seems to create a symbol called `_dep_message_<module_name>`. What if `lsnames` avoids recursing into modules which have a corresponding `_dep_message`?

By the way, look at the compatibility note: Julia 1.5 will not complain without an explicit `--depwarn=yes` flag.

**Comment by orialb** [comment]
Thanks for looking into it. I'll try to implement your suggestion when I find the time  (at the moment I'm just using the patch I suggested above on my own machine to make Snail usable with Revise).

Just to note that it is not only deprecation warnings, I also encounter something like this triggered by code completion when working on my own module:
<img width="992" alt="image" src="https://user-images.githubusercontent.com/1208196/80650290-04d30880-8a74-11ea-8df9-204217b24469.png">

This other type of warnings seems to be less of a hassle than the deprecation warnings, because it seems to be triggered only once per session (not sure exactly). However it will be nice to make these warnings go away as well at some point.

**Comment by gcv** [comment]
Since deprecation warnings aren’t the only nuisance, your `no_stderr` macro is more appealing. Should we both filter deprecated APIs _and_ suppress stderr? Discouraging use of deprecated stuff by omitting it from completion makes sense, but the filter I propose is fragile because it tracks Julia internals. What do you think?

**Comment by orialb** [comment]
I think it makes sense to filter out deprecated things from completion (to the extent that we are able to do so), after all one should stop using these things :) 
From a user perspective I don't see any reason why the user would be interested in getting warnings/errors triggered by `lsnames` so I think just redirecting those somewhere else is also a good thing to do. It might be necessary to get those for debugging of Snail, but this can be done by disabling `no_stderr` either manually or by some debug flag. 
We do have to make sure that this redirection that happens at every completion doesn't cause any performance issues or other issues, but I guess this can be done only via testing it for a while?

**Comment by orialb** [comment]
Regarding the fragility of the filter, maybe the question is what happens when it breaks? 
If we can write it in such a way that completion still works and in the worst case the filter just stops having any affect then maybe its fine as an experimental feature? But if there is a chance that it will break completion then I think it's not worth the risk.

Also, if I understand correctly the filter you suggest is able to only filter out deprecated modules (as opposed to functions), right? I don't know how common it is that a whole module is deprecated (again as opposed to functions), so maybe it's also something to try to figure out.

**Comment by gcv** [comment]
The filter should, in theory, not cause problems if Julia changes its internal deprecation flagging mechanism.

Filtering out functions shouldn't be necessary, since the deprecation warning should only appear when the functions are called, not enumerated. Julia's internals don't seem to have any deprecation-flagging metadata (though I wouldn't be surprised if a future version of Julia acquired such a thing).

Let's get your `no_stderr` patch out. I think it's the right thing to do anyway. Want to open a PR with it?

**Comment by orialb** [comment]
> Want to open a PR with it?
sure. I'll do it at some point during the weekend.

**Comment by orialb** [comment]
hmm, it seems that this `@no_stderr` macro is not really suppressing all types of errors/warnings properly (also the ones in Suppressor.jl don't seem to work properly with Julia 1.3.1). It does suppress those warnings from Revise above but not other types of errors. I'll have to investigate this a bit more, since if we put some macro like this we might as well make sure it really suppresses all errors and warnings. 

As a side note, these deprecation warnings don't seem to be triggered by `lsnames` on Julia 1.4.1 anymore (but if I call `Revise.FileModules` manually I do see the deprecation warning so it is still there).

**Comment by gcv** [comment]
If `lsnames` does not cause warnings to appear on Julia 1.4.1 at all, do we need to patch around it at all? While I'd like to support the LTS of Julia, I'm reluctant to add _too_ much obscure code to do it.

**Comment by orialb** [comment]
sorry I made a mistake. I checked again on 1.4.1 and the warning does appear when calling `lsnames` with `imported=true` .  I verified that this will be gone on Julia 1.5 (nightly), probably due to the fact that deprecation warnings are off by default, as you pointed out above. 

I also figured out some things regarding the `no_stderr` macro. The way I wrote it, it will suppress certain warnings written to `stderr` but not warnings which are triggered by `@warn`.  In order to suppress also `@warn` warnings, one also has to temporarily change the current logger, but this incurs some performance penalty which I don't think we want. 
Without redirecting the logger I checked that there is almost no performance difference when using `@no_stderr` with `lsnames`.  
I don't know if those `@warn` warnings can even be triggered by `lsnames`, I think we probably don't need to worry about them so much, so the current `no_stderr` macro should be ok. 

>While I'd like to support the LTS of Julia, I'm reluctant to add too much obscure code to do it.

I think you are right. If I am the only person experiencing such problems I am also fine with just having this `no_stderr` patch on my personal fork until 1.5 comes out which should solve this specific problem with module deprecation warnings (although if someones starts Julia with depwarn they will experience a problem I guess).

**Comment by dsweber2** [comment]
> I am the only person experiencing such problems 

This has also been causing some extreme delays in company's execution for me. I'm afraid I'm not too comfortable with emacs' internals, so I'm having difficulty actually getting @orialb 's solution to work (probably just stuck it in the wrong spot or something). I'm on 20200531.2032 installed via elpa.

**Comment by orialb** [comment]
@dsweber2  I would actually not use the patch suggested here, I noticed it can sometimes lead to "too many open files" errors due to too many temporary files being generated (I think this is the reason).
The best workaround for me at the moment is to just disable the `lsnames` based completion (there are currently too methods that provide completions, one of them is causing this errors), this can be done by commenting out:
https://github.com/gcv/julia-snail/blob/f4f483e14c3e8ff1b0311056cd072a4ba9c8f886/julia-snail.el#L1051-L1052

**Comment by gcv** [comment]
@orialb: Does removing `lsnames` based completion make all these warnings go away completely? What about the way `lsnames` is used for xref?

(Context: It's really looking like we just need to turn off `lsnames` completion. I'm trying to get as much information as I can before making a final decision.)

**Comment by orialb** [comment]
Removing the `lsnames` completion removed all the warnings I could see when working on my code with Revise. I haven't been using xref functionality extensively (got used to not having this functionality when writing Julia code and just using project based grep before, and I guess old habits die hard) but from a quick check I made now it didn't cause any warnings.

**Comment by gcv** [comment]
`lsnames`-based completion is now off the island. https://github.com/gcv/julia-snail/commit/e2a6e0cdda849f78f43a506cdede054c6c8dfca6 — this is now in MELPA. @dsweber2, this should fix the problem you ran into.

**Comment by dsweber2** [comment]
yep! I can now use company again, thanks for the help.
