### ISSUE TITLE
can't load macro due to parser error

### ISSUE THREAD

**Issue by dahtah** [gcv/julia-snail#31]
MWE: try loading the definition for "@show" using julia-snail, ie.
```
macro show(exs...)
    blk = Expr(:block)
    for ex in exs
        push!(blk.args, :(println($(sprint(show_unquoted,ex)*" = "),
                                  repr(begin value=$(esc(ex)) end))))
    end
    isempty(exs) || push!(blk.args, :value)
    return blk
end
```
then C-c C-k (or C-c C-c) results in an error. Stack trace is a mess but it seems parser-related. I think it gets confused around the weird syntax in the println part.

**Comment by gcv** [comment]
Fixed with the parser changes introduced in #33 and 34498596550b0f81.
