### ISSUE TITLE
Installing julia-snail with straight.el

### ISSUE THREAD

**Issue by 4aHxKzD** [gcv/julia-snail#38]
I'm having trouble using `julia-snail` with the `straight.el` package manager, but I don't know which package is giving me the error.
After `straight.el` installs `julia-snail` and I try to start `julia-snail-mode` in a Julia buffer I get the following messages:

```
File mode specification error: (error Autoloading file /home/dav/.emacs.d/straight/build/julia-snail/julia-snail.elc failed to define function julia-snail-mode)
command-execute: Autoloading file /home/dav/.emacs.d/straight/build/julia-snail/julia-snail.elc failed to define function julia-snail-mode
```

This is how I install the packages:

``` Emacs-lisp

(use-package vterm
   :straight t
   :defer t)

(use-package julia-snail
   :straight t
   :defer t
   :hook (julia-mode . julia-snail-mode))
```

My software versions are:
- Emacs 27.1
- Julia 1.5

**Comment by gcv** [comment]
I think it's the problem where you have to install `vterm` first manually. It's noted in the README under [https://github.com/gcv/julia-snail/#installation](Installation steps 3 and 4).

To fix, make sure you get vterm fully running first. Then you'll need to undo the result of the strange Emacs packaging bug. (The symptom is an abnormally small `julia-snail.elc` file, the compiler just didn't finish working.) The best and easiest thing is to delete the `julia-snail` package and reinstall it.

**Comment by 4aHxKzD** [comment]
Thanks :+1:

**Comment by 4aHxKzD** [comment]
I changed to this

```Emacs lisp

(use-package vterm
   :straight t)

(use-package julia-snail
   :straight t
   :requires vterm
   :hook (julia-mode . julia-snail-mode))

```
