### ISSUE TITLE
Calling PyCall

### ISSUE THREAD

**Issue by kadir-gunel** [gcv/julia-snail#40]
Hello, 

Is there any way that we can first call python virtualenv and then connect to julia ? 

B.R.

**Comment by gcv** [comment]
Please try using [auto-virtualenv](https://github.com/marcwebbie/auto-virtualenv). If it’s all set up correctly, Snail’s invocation of `julia` should pick up the Python environment.

**Comment by kadir-gunel** [comment]
Thank you @gcv
