### ISSUE TITLE
better unicode substitution

### ISSUE THREAD

**Issue by dahtah** [gcv/julia-snail#43]
More of a tip, not sure if it should be a feature? Maybe to be included in the documentation?
Anyway: there's a better way to insert unicode characters, and it's [xah-math-input](https://github.com/xahlee/xah-math-input). Basically, you type a (Roman) letter like "a", then shift-spc, and it substitutes the Greek equivalent, here α. Much better than \alpha then Tab, especially when you get to \varepsilon. Here's a function that makes it work in the REPL as well:
```
  (defun julia-snail--xah-math-substitute ()
    (interactive)
    (save-excursion
      (backward-char 1)
      (let ((newchar (xah-math-input--abbr-to-symbol (thing-at-point 'char t))))
        (forward-char 1)
        (vterm-send-backspace)
        (vterm-send-string newchar)
        )
      )) 
```
and you can add 
```
(define-key julia-snail-repl-mode-map (kbd "S-SPC") 'julia-snail--xah-math-substitute)
```
in your julia-snail-mode-hook to make it work.

**Comment by gcv** [comment]
Added to the wiki (which is now linked to in the README): https://github.com/gcv/julia-snail/wiki/Tips-and-Tricks#alternative-unicode-substitution
