### ISSUE TITLE
small bug in parser

### ISSUE THREAD

**Issue by dahtah** [gcv/julia-snail#48]
This occurs when using LaTeXStrings.jl with autocompletion with company-capf turned on. Typing 
`L"\a"` 
results in some kind of string escaping error 
```
Base.Meta.ParseError("\"\\\" is not a unary operator")

parse(::String, ::Int64; greedy::Bool, raise::Bool, depwarn::Bool) at meta.jl:184
parse at meta.jl:176 [inlined]
parse(::String; raise::Bool, depwarn::Bool) at meta.jl:215
parse(::String) at meta.jl:215
macro expansion at JuliaSnail.jl:540 [inlined]
(::Main.JuliaSnail.var"#33#38"{Sockets.TCPSocket})() at task.jl:356
```

**Comment by gcv** [comment]
I'm not entirely sure what's going on here. The error seems to happen here: https://github.com/gcv/julia-snail/blob/03b4296ba7151963eb3c850f3314b02644101f51/JuliaSnail.jl#L540, i.e. `Meta.parse` doesn't like the fully escaped string passed to it. It might be related to backslash quoting complexity in `julia-snail-repl-completion-at-point`. @orialb, do you have any ideas?

**Comment by orialb** [comment]
sorry for the late response, just saw this now. It seems that indeed there is some conflict between properly escaping the string quotes and the backslash. I will try to find some time this week to take a look.

**Comment by gcv** [comment]
@dahtah: Looking into this report again, and I can't reproduce it any more. Julia 1.6.2, latest Snail.

**Comment by gcv** [comment]
Please reopen this ticket if you still see this bug.
