### ISSUE TITLE
julia-snail-doc-lookup failing if beginning of file

### ISSUE THREAD

**Issue by nico202** [gcv/julia-snail#50]
Hi, calling `julia-snail-doc-lookup` is failing in a buffer containing
```
println("Hello")
```
with the point on `println`.  Turns out `julia-snail--identifier-at-point` is calling `julia-snail--bslash-before-p` with an argument of 1, so `(char-before 1)` is failing.

**Comment by gcv** [comment]
Pretty sure this bug was fixed in 7c76d58ca45016d8c5bde9c7d737bbb9f458b75d back in November. Please confirm you have a recent version of Snail.

**Comment by nico202** [comment]
My bad for not checking master.  I'm on rc4, I'll upgrade to rc5.  Thanks and sorry
