### ISSUE TITLE
CSTParser UndefVarError: Call not defined

### ISSUE THREAD

**Issue by duzaichuan** [gcv/julia-snail#52]
Emacs 27.2 Julia 1.6.1
Any hint?

ERROR: UndefVarError: Call not defined
Stacktrace:
 [1] (::Main.JuliaSnail.CST.var"#1#2"{String, Dict{Any, Any}})(node::CSTParser.EXPR, modules::Vector{Any})
   @ Main.JuliaSnail.CST ~/.emacs.d/straight/repos/julia-snail/JuliaSnail.jl:455 [2] (::Main.JuliaSnail.CST.var"#1#2"{String, Dict{Any, Any}})(node::CSTParser.EXPR)
   @ Main.JuliaSnail.CST ~/.emacs.d/straight/repos/julia-snail/JuliaSnail.jl:454 [3] includesin(encodedbuf::String, path::String)
   @ Main.JuliaSnail.CST ~/.emacs.d/straight/repos/julia-snail/JuliaSnail.jl:469 [4] includesin
   @ ~/.emacs.d/straight/repos/julia-snail/JuliaSnail.jl:449 [inlined]
 [5] forcecompile
   @ ~/.emacs.d/straight/repos/julia-snail/JuliaSnail.jl:487 [inlined]
 [6] start(port::Int64)
   @ Main.JuliaSnail ~/.emacs.d/straight/repos/julia-snail/JuliaSnail.jl:608
 [7] top-level scope
   @ REPL[1]:1

**Comment by gcv** [comment]
What version of CSTParser do you have activated?

**Comment by duzaichuan** [comment]
Oh...I see. I use 3.2 instead of 2.5, cuz I installed the LanguageServer.jl that depends on the latest version of CSTParser.

**Comment by gcv** [comment]
I almost finished a fix for CSTParser 3 compatibility. Should be out in the next couple of days.

**Comment by duzaichuan** [comment]
Solved! Thanks for working on this excellent project.
