### ISSUE TITLE
Cannot evaluate multi-line regions with C-c C-r

### ISSUE THREAD

**Issue by prittjam** [gcv/julia-snail#53]
emacs 27.2
julia 1.5.3
julia-snail 20210807.406 (latest from MELPA)

Latest version cannot evaluate multi-line regions. Single-line regions can still be evaluated, but this is very tedious.

The error is: 

Base.Meta.ParseError("extra token after end of expression")

parse(::String; raise::Bool, depwarn::Bool) at meta.jl:220
parse at meta.jl:215 [inlined]
eval_tmpfile(::String, ::Array{Symbol,1}, ::String, ::Int64) at JuliaSnail.jl:187
top-level scope at none:1
eval at boot.jl:331 [inlined]
eval_in_module(::Array{Symbol,1}, ::Expr) at JuliaSnail.jl:160
macro expansion at JuliaSnail.jl:697 [inlined]
(::Main.JuliaSnail.var"#28#32"{Sockets.TCPSocket})() at task.jl:356

**Comment by gcv** [comment]
Haha, nice! Release version 1.1.0 lasted less than a day. This bug should be fixed in 1.1.1 (c650a6c). It's in MELPA now. Thank you for the bug report, and let me know if that fix works for you.

**Comment by prittjam** [comment]
It works! thanks for the fast fix.
