### ISSUE TITLE
Strange cursor behavior in REPL

### ISSUE THREAD

**Issue by prittjam** [gcv/julia-snail#57]
emacs 27.2
julia 1.6.2
julia-snail   20210818.310

The cursor seems to be behind the edited character by one letter. The bug makes editing in the REPL difficult.

**Comment by gcv** [comment]
Sounds like a vterm problem. Try deleting the emacs-libvterm package, restarting Emacs, and reinstalling it from scratch.

**Comment by prittjam** [comment]
It fixed itself.
