### ISSUE TITLE
Buffer does not parse on legal julia source code

### ISSUE THREAD

**Issue by jlapeyre** [gcv/julia-snail#6]
I am unable to run `julia-snail-run-top-level-form` on any function (form) in a file if the following
line is in the file as well

```
many_rolls(n) = (+(roll_pair()...) for _ in 1:n)
```

The error is "Buffer does not parse; check Julia syntax".

**Comment by gcv** [comment]
Disclaimer: the Snail parser is the result of wanting structural information about the code of a language which has no formal grammar specification. 🤷🏻‍♂️ Which makes robust parsing of an arbitrary expression all but impossible. The parser has to rely on tricks and approximations.

Anyway, I pushed a change which should help this syntax. It should now be in MELPA. Please let me know if it works.

**Comment by gcv** [comment]
Please reopen if this still does not work.
