### ISSUE TITLE
Unable to perform `julia-snail-send-region` and `julia-snail-doc-lookup`

### ISSUE THREAD

**Issue by tencnivel** [gcv/julia-snail#61]
I have a very simple project with the following structure 
```
 .
├── main.jl
├── Project.toml
└── src
    └── MyJuliaProject.jl
```

main.jl is used to invoke what's in module `MyJuliaProject`

main.jl:
```
using Pkg
Pkg.activate(".")
using Revise
using MyJuliaProject

MyJuliaProject.greet()
```
`julia-snail-send-line` works fine but `julia-snail-send-region` does not. 
I get the following error after a few seconds : 
`julia-snail--send-to-server: Snail command timed out`

Here are the packages installed:
```
julia-mode         20211023.1434 dependency            Major mode for editing Julia source code
julia-snail        20210818.310  installed             Julia Snail
vterm              20210908.640  installed             Fully-featured terminal emulator
```

In my `init.el`, I have:
```
(use-package vterm
  :ensure t)
(use-package julia-snail
  :ensure t
  :requires vterm
  :hook (julia-mode . julia-snail-mode))
```

in the `.dir-locals.el` in my project folder, I have:
```
((julia-mode
  (julia-snail-executable . "/home/myuser/IDE/julia/julia-1.6.3/bin/julia"))
  )
```

**Comment by gcv** [comment]
Is this the same environment as #62 ?  If so, let's get that sorted out first.

**Comment by tencnivel** [comment]
it works now
