### ISSUE TITLE
Buffer *julia* process has no process

### ISSUE THREAD

**Issue by jtrakk** [gcv/julia-snail#64]
Running julia-snail created a vterm buffer named `*julia*` and executed 

```
julia> JuliaSnail.start(10011);
```

`julia-snail-send-line` works but `julia-snail-send-buffer-file` says 

```
Buffer *julia* process has no process
```

as do all the other `send-` functions.

**Comment by jtrakk** [comment]
Turns out I'm on an old version. Will reopen if upgrading doesn't fix it.

**Comment by g-gundam** [comment]
In case anyone else runs into this, I had to update [eat](https://codeberg.org/akib/emacs-eat) in addtion to julia-snail before it would work.
