### ISSUE TITLE
unable to parse toplevel block

### ISSUE THREAD

**Issue by tpapp** [gcv/julia-snail#7]
Using the latest from MELPA (20200312.2044), on a file that contains
```julia
1 + 1
```
when I try <kbc>C-c C-c</kbd> I get
```emacs-lisp
Debugger entered--Lisp error: (error "Unable to parse top-level block")
  signal(error ("Unable to parse top-level block"))
  error("Unable to parse top-level block")
  julia-snail-parser--query-top-level-block(nil)
  julia-snail-parser-query(#<buffer tmp.jl> 1 :top-level-block)
  julia-snail-send-top-level-form()
  funcall-interactively(julia-snail-send-top-level-form)
  call-interactively(julia-snail-send-top-level-form nil nil)
  command-execute(julia-snail-send-top-level-form)
```
Emacs 26.3.

**Comment by gcv** [comment]
This results from the same parser limitations as https://github.com/gcv/julia-snail/issues/5. `C-c C-c` only works on `end`-terminated blocks.

I changed a bunch of `error` calls to `user-error` so you don't get caught in the debugger when this happens (`debug-on-error` is a weird beast and I've had problems with it and consistency of behavior) and improved the documentation and error message in this case.
