### ISSUE TITLE
cannot autoload julia-snail 

### ISSUE THREAD

**Issue by nesteiner** [gcv/julia-snail#75]
maybe is the problem of my program ability on `emacs-lisp`, when I type this code, `julia-snail` can't autoload when loading a julia file 
```emacs-lisp
(use-package julia-mode
  :config
  (setq julia-repl-switches nil
	julia-snail-extra-args nil
	julia-indent-offset 2)
  :commands julia-snail-mode)


(use-package julia-snail
  :ensure t
  :after julia-mode
  :requires vterm
  :hook (julia-mode-hook . julia-snail-mode)
  :config
  (setq-default julia-snail-extra-args "--sysimage /home/steiner/.julia-images/julia-dev.so"))
```

I remember that it was ok, after i use byte compile emacs-lisp file, it does not work since then

**Comment by gcv** [comment]
How large is the `julia-snail.elc` byte-compiled file? Sometimes the byte compiler does not compile the whole file. If it’s only a few hundred bytes, delete it, make sure vterm is fully loaded (`M-x vterm`), and recompile `julia-snail.el`.

**Comment by nesteiner** [comment]
still not work,  
![2022-01-30 21-14-02 的屏幕截图](https://user-images.githubusercontent.com/46296608/151701207-c180b0c3-b3dc-4893-93f1-9ce05ee37fa6.png)
does that work on your system ?

**Comment by gcv** [comment]
Is `init-julia.el` the file with your `use-package` forms? Please post the size of your `julia-snail.el*` files. Let’s first make sure the Snail installation is not broken.

**Comment by nesteiner** [comment]
![2022-01-31 18-33-52 的屏幕截图](https://user-images.githubusercontent.com/46296608/151778416-42c2061d-221d-47b2-b41b-0d5c45403644.png)

**Comment by nesteiner** [comment]
what the fuck ? I  just install the julia-snail 20220117.2310  
but found that when typing `julia-snail`, I can't open julia on vterm , the emacs tells me that 
```

**Comment by nesteiner** [comment]
Starting Julia process and loading Snail...
user-error: The vterm buffer is inactive; double-check julia-snail-executable path
```

????

**Comment by gcv** [comment]
That's still an `init-julia.el` file. I'm asking for `ls -la` output of your Snail installation directory, not your configuration code.

**Comment by nesteiner** [comment]
here you are
![Uploading 2022-02-01 01-49-46 的屏幕截图.png…]()

**Comment by gcv** [comment]
There's nothing attached to your message.

**Comment by nesteiner** [comment]
![2022-02-01 01-49-46 的屏幕截图](https://user-images.githubusercontent.com/46296608/151915051-4f1f0ad3-788b-4d79-9358-2fe11b287134.png)

**Comment by gcv** [comment]
That's the installation directory. I want to see the files inside it, specifically the `julia-snail.elc` file.

**Comment by nesteiner** [comment]
![2022-02-01 13-41-16 的屏幕截图](https://user-images.githubusercontent.com/46296608/151918473-255cc6c5-8345-4324-ae09-8dc6df55dba7.png)

**Comment by gcv** [comment]
Your installation looks good.

Can you post the values of `julia-mode-hook` both when you do and do not have the byte-compiled `init-julia` file available? I want to understand if the byte compiler is messing something up for your configuration file.

**Comment by nesteiner** [comment]
![2022-02-01 13-52-00 的屏幕截图](https://user-images.githubusercontent.com/46296608/151919324-d0cfa1aa-e000-4da9-80a1-9a873c0e0cf5.png)


both hook are the same like this, maybe it the problem of my configuration code ?

**Comment by nesteiner** [comment]
holy shit, this code works !
```emacs-lisp
(use-package julia-mode
  :hook (julia-mode . julia-snail-mode)
  :config
  (setq julia-repl-switches nil
	julia-snail-extra-args nil
	julia-indent-offset 2)
  :commands julia-snail-mode)
```

I think I have took you too much time

**Comment by gcv** [comment]
Very interesting. You're the second person to report this problem and this exact workaround (see #70). For completeness and so I can look into this later, what version of Emacs are you using? What OS? Do you have native compilation enabled?

**Comment by nesteiner** [comment]
maybe we are not so familiar with emacs-lisp, I think the major mode once loaded, so that its hook can be called.

**Comment by gcv** [comment]
What we don't understand is `use-package`. I managed to reproduce the problem you reported. Remove `:requires vterm` from your original example, and it should work.

It looks like this bug occurs because of `:requires`: https://github.com/jwiegley/use-package#prevent-loading-if-dependencies-are-missing — so if your `(use-package vterm)` form is not evaluated first, _even if the vterm package is installed_, julia-snail is not loaded. It looks like your case and #70 both happened because of this.

I'll update the Snail README and remove `:requires vterm` and see if that causes a separate set of problems.

**Comment by nesteiner** [comment]
@gcv hey I think I found the problem, using this code
```julia
(use-package julia-snail
  :ensure t
  :after julia-mode
  :requires vterm
  :config
  (setq-default julia-snail-extra-args "--sysimage /home/steiner/.julia-images/julia-dev.so")
  (setq julia-snail-executable "/usr/local/bin/julia"))
```

and I found that when load julia file, watching the local varibale and the `julia-snail-extra-args` is nil, so I think this code is not loaded at all

**Comment by nesteiner** [comment]
how about trying this code, and check the local buffer variable, you will find out

**Comment by gcv** [comment]
You need to remove `require :vterm` from there. I discovered this upthread: https://github.com/gcv/julia-snail/issues/75#issuecomment-1026930872
