### ISSUE TITLE
Org mode support

### ISSUE THREAD

**Issue by MasonProtter** [gcv/julia-snail#79]
It'd be great of we could make an `ob-julia-snail` mode using the infrastructure here. I think most of what is needed is already implemented.

**Comment by gcv** [comment]
I agree. PRs very much welcome. I’m not familiar with writing Org Babel modes, but there’s probably a challenge involved here in wrangling the connection buffers. (We don’t want to restart Julia at every evaluation.)

I know it’s not as good as true Babel integration, but the [code cells](https://github.com/gcv/julia-snail#code-cells-integration-notebook-mode) works pretty well for me.

**Comment by MasonProtter** [comment]
Closed by https://github.com/gcv/julia-snail/pull/86
