### ISSUE TITLE
Error starting up `julia-snail` in a non-`.jl` file

### ISSUE THREAD

**Issue by MasonProtter** [gcv/julia-snail#85]
I'm making a `ob-julia` mode using `julia-snail` and one problem I'm encountering is that if I do `M-x julia-snail` in a `.org` file, I get an error
```
Wrong type argument: stringp, nil
```
originating from 
```elisp
(file-remote-p (buffer-file-name julia-snail--repl-go-back-target) 'method)
```
in https://github.com/gcv/julia-snail/blob/master/julia-snail.el#L561

I see this just just about dealing with docker, so I was able to fix the issue by just replacing the whole `if` expressions `""`, but it'd be good if `julia-snail` handled this itself. I'm not exactly sure what is going wrong. Everything works fine for me in `.jl` files.

**Comment by gcv** [comment]
This should be fixed in commit d6d0ded.
