### ISSUE TITLE
How to enable `ob-julia` globally?

### ISSUE THREAD

**Issue by femtomc** [gcv/julia-snail#89]
This is less of an issue, and more of a question (although the answer could certainly go in the appropriate section of the README).

I setup snail and got it working — and I want to use it with `org-babel` for some of my literate notes. In my eMacs config, I set the snail extensions variable to include `ob-julia`.

however, I’ve found that I’m forced to place the “use `ob-julia` header” at the top of my org files, which breaks `org-roam` (which I’m using to track cross references)

how do I set this globally? So that org source blocks automatically just use snail instead of whatever the default via babel is?

**Comment by gcv** [comment]
How exactly did you set up `julia-snail-extensions` globally?

**Comment by femtomc** [comment]
I'm using `doom` so:

```
(use-package! julia-snail
  :ensure t
  :hook (julia-mode . julia-snail-mode))
(add-to-list 'display-buffer-alist
             '("\\*julia" (display-buffer-reuse-window display-buffer-same-window)))
(setq julia-snail-extensions '(repl-history formatter ob-julia))
```
in my `config.el`

**Comment by gcv** [comment]
`julia-snail-extensions` is a buffer-local variable (so it could be set individually per-project), so if you want to give it a global default you need to use `setq-default` instead of `setq`.

**Comment by femtomc** [comment]
@gcv thank you!
