### ISSUE TITLE
Feature Request - Markdown formatted completion overlays

### ISSUE THREAD

**Issue by kiranshila** [gcv/julia-snail#91]
Currently, during completion, the raw docstrings are displayed 
![image](https://user-images.githubusercontent.com/6305359/165184238-35964a36-cebf-4144-a112-337a5efc9eb0.png)
It would be nice to have this formatted with `markdown-mode` like rust-analyzer does 
![image](https://user-images.githubusercontent.com/6305359/165184520-940388da-c59c-4d2b-980f-ae8e508c2c3d.png)

**Comment by gcv** [comment]
Should be available in MELPA in a couple of hours: https://github.com/gcv/julia-snail/commit/d0d356261667c31bf093b535ab9678d0a8c78ff5

Completion docstrings now also support `corfu-doc`.
