### ISSUE TITLE
error when evaluating code in .jl buffers

### ISSUE THREAD

**Issue by MasonProtter** [gcv/julia-snail#94]
On the master version currently, if I select a region and do `julia-snail-send-___` (e.g. `dwim` or `region`), I get a message saying
```
error in process filter: No catch for tag: julia-snail--server-filter-error, (error "Keyword argument :face not one of (:point :around :width :height :min-height :max-width :truncate :margin :margin-left :margin-right :scroll-bar :parent :parent-offset :nowait :nostrip :prompt)")
```
I tried to debug it, but I can't get the debugger to actually catch the error.

**Comment by gcv** [comment]
I'll debug later today. Does the error still happen if you turn off display popups?

**Comment by MasonProtter** [comment]
Disabling the display popups avoids the error.

**Comment by gcv** [comment]
What version of [popup](https://github.com/auto-complete/popup-el) do you have installed? You must have something from before [this commit](https://github.com/auto-complete/popup-el/commit/fbef25196dcfd7fb4c5c14cd1f339ba28132a8f9). I put version 0.5.9 as a `Package-Requires` dependency in `julia-snail.el`, but maybe the version number does nothing if the package is already installed.

**Comment by gcv** [comment]
Please reopen if updating the popup library does not resolve the problem.
