### ISSUE TITLE
I don't think put evaluate result above cursor is a good idea

### ISSUE THREAD

**Issue by nesteiner** [gcv/julia-snail#96]
![图片](https://user-images.githubusercontent.com/46296608/169685732-03982d10-2800-451e-a7cb-56aa7ee35aa3.png)

when the result is too large, the frame can't hold it and it can just ignore lots of content, so can you give some adjustment ?

**Comment by gcv** [comment]
Try setting `julia-snail-popup-display-eval-results` to `:change`. It restricts the popup to a single line.

If that's not what you want, what kind of adjustment do you have in mind? User configurable maximum width and height for the popup? Or something more sophisticated?

**Comment by nesteiner** [comment]
I have set that, and found something wrong 
```
error in process filter: julia-snail--server-response-filter: No catch for tag: julia-snail--server-filter-error, (args-out-of-range 229 229)
```

this is the error i meet

**Comment by nesteiner** [comment]
by the way, even I don' set the `julia-snail-popup-display-eval-results`, the result is the same  
and why there are two frame ? I think it should disappear when press any key  
![图片](https://user-images.githubusercontent.com/46296608/171985424-4f493bfb-4742-4558-bcae-d47d223f4feb.png)

**Comment by gcv** [comment]
I'm not sure what is going on. Maybe you have some stale .elc files floating around? Please uninstall Snail fully (make sure its directory is gone), restart Emacs, and reinstall Snail. Also, please post your exact configuration for Snail and julia-mode. Also, what version of Emacs are you on?

**Comment by nesteiner** [comment]
I think I found the problem,  this is the code after modified  
```emacs-lisp
(use-package julia-mode
  :hook (julia-mode . julia-snail-mode)
  :config
  (setq julia-repl-switches nil
	julia-snail-extra-args nil
	julia-indent-offset 2
	;; julia-snail-popup-display-eval-results :change
	julia-snail-executable "/home/steiner/.local/bin/julia")
  (setenv "JULIA_PKG_SERVER" "https://mirrors.tuna.tsinghua.edu.cn/julia")
  (setq-default julia-snail-extra-args "--sysimage /home/steiner/.julia/images/julia-dev.so")
  :commands julia-snail-mode)
```

just comment the `julia-snail-popup-display-eval-results` is ok

**Comment by gcv** [comment]
Maybe your session ended up in a bad state? The following code will clean it up:

```elisp
(cl-loop for popup in julia-snail--popups do (popup-delete popup))
```
